let loremP = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque facilisis, metus vel tincidunt mattis, ipsum purus consectetur orci, at aliquam turpis arcu quis ipsum. Vivamus lobortis euismod mi nec sollicitudin. Ut imperdiet, tellus vel fringilla bibendum, quam eros malesuada mauris, sed aliquam massa sapien sit amet velit. Praesent fringilla velit tellus, eu sollicitudin ipsum viverra non. Nam vitae egestas elit. Sed congue neque sollicitudin dictum aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet id sapien ut pharetra. Sed vestibulum massa ac sem sollicitudin, vel consectetur nulla consectetur. Donec vulputate enim id sollicitudin hendrerit. Morbi purus magna, luctus eget suscipit sit amet, malesuada vitae nisi. Fusce condimentum ac diam eu molestie. Mauris nec pulvinar enim. Nunc diam nisl, ultricies eget orci ac, hendrerit gravida arcu. Nam cursus, ipsum malesuada iaculis ornare, leo massa ornare mi, in efficitur libero nisl non neque. Curabitur condimentum elementum ante at malesuada.
"""

let lorem = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed massa purus, ullamcorper non dolor eu, fringilla semper ipsum. Fusce ac rutrum nunc. Vivamus elit tortor, mattis a diam eget, elementum malesuada erat. In aliquam velit et dui dictum, eget pulvinar quam ultrices. Nullam vel ex mollis, convallis diam eget, posuere urna. Sed et viverra sapien. Ut ut fringilla massa. Nunc et lobortis tortor. Vivamus interdum eros sed diam venenatis gravida. Cras maximus pulvinar enim, quis accumsan turpis sagittis vel. Praesent sit amet libero commodo, pulvinar ipsum eget, hendrerit justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin placerat orci elit. Ut in tristique mauris, non tempor dolor.

Nunc a lectus bibendum, efficitur libero quis, ultrices odio. Donec semper, sem ac laoreet interdum, odio orci mattis justo, nec lacinia lorem lectus interdum massa. Nullam velit augue, congue ut lorem at, rutrum interdum turpis. Aliquam convallis feugiat porttitor. Pellentesque dictum fringilla tellus faucibus pretium. In quam sem, pretium eu tortor eu, consectetur tincidunt augue. Suspendisse blandit fringilla libero, id porta ipsum finibus nec. Maecenas sit amet ullamcorper tortor, eu semper est. Curabitur mattis nunc a orci ultricies, eu consequat tellus egestas. Vivamus placerat quis augue eget dapibus. Morbi nibh ex, tempor ut nunc at, malesuada viverra neque. Nam sed massa purus. Pellentesque a ex id magna pellentesque euismod eget et neque. Praesent auctor ultricies erat eget vulputate. Aliquam id purus sit amet risus imperdiet aliquet.

Ut tristique ac sapien vel efficitur. In hac habitasse platea dictumst. Aliquam at nibh nibh. Nam fringilla tortor et massa mattis aliquet. Fusce tempus ante sed metus efficitur aliquam. Aenean feugiat nisi sed massa lobortis sodales. Aliquam porta ut nisi ut mollis.

Praesent pulvinar quam a orci feugiat, vitae auctor elit dictum. Nullam consectetur enim vehicula quam pellentesque porta quis sit amet leo. Nunc pharetra pellentesque metus, volutpat sollicitudin neque eleifend sit amet. Nunc convallis nulla sed leo feugiat, rhoncus porta risus eleifend. Vivamus ultrices bibendum magna, sit amet congue augue mollis rhoncus. Nullam turpis odio, aliquam eu ante sed, pellentesque iaculis nulla. Curabitur mollis iaculis auctor. Aenean malesuada tortor eu augue elementum efficitur. Duis vitae orci scelerisque, convallis felis quis, malesuada eros. Praesent sit amet ligula blandit massa eleifend tincidunt at viverra nisi. Pellentesque finibus ultricies mi eget porta. Mauris sit amet est sed ligula vehicula facilisis sed sed augue. Donec sollicitudin tellus lectus, nec volutpat libero pellentesque non. Ut efficitur justo mi, eu lobortis nisi vulputate et. Nam id eros enim. Duis eget finibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in sollicitudin neque, id ultricies tellus. Nam malesuada est in rhoncus condimentum. Donec viverra tincidunt ligula. Vestibulum iaculis eget nunc ut tincidunt. Nunc malesuada fermentum erat, ut ultricies elit. Sed vitae vehicula velit. Donec placerat est pellentesque posuere suscipit. Suspendisse aliquet sapien vitae consequat tristique. Ut id odio mi. In sit amet lectus consequat, facilisis mi ac, volutpat augue. Pellentesque commodo egestas elit, nec pretium dolor faucibus vitae. Quisque sed magna metus. Vestibulum ullamcorper nibh sollicitudin lorem vehicula, consectetur auctor nunc lobortis. Nulla laoreet tellus ut fermentum tincidunt.
"""
